version: '3'
services:
  mongo-db:
    image: mongo:4.4.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27020:27017
    command: --wiredTigerCacheSizeGB 1.5
  test-mongo-db:
    image: mongo:4.4.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admintest
      - MONGO_INITDB_ROOT_PASSWORD=admintest
    ports:
      - 27055:27017
    command: --wiredTigerCacheSizeGB 1.5
