name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Prebuild
        run: rimraf dist
      - name: Build
        run: yarn build
      - name: Format
        run: yarn format
      - name: Start
        run: yarn start
      - name: Development
        run: yarn start:dev
      - name: Debug
        run: yarn start:debug
      - name: Production
        run: yarn start:prod
      - name: Linter
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Watch test's
        run: yarn test:watch
      - name: Test coverage
        run: yarn test:cov
      - name: Test debug
        run: yarn test:debug
      - name: Test e2e
        run: yarn test:e2e
