name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_ROOT_USERNAME: admintest
      MONGO_INITDB_ROOT_PASSWORD: admintest
      MONGO_AUTHDATABASE: admintest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Linter
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Test e2e
        run: yarn test:e2e
